-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('how-many-karens-are-left', 'How Many Karens Are Left?', 'The internet pictures Karen as a 45-year-old at a returns counter. The data says she is closer to 65 — and there are almost no new ones.', '<p>In 1965, Karen was the third most popular name for girls in America. 32,869 of them were born that year — about 1.9% of all baby girls.</p>
<p>By 2020, the year the meme peaked, the name had fallen to #821. More than 800 names ranked above it.</p>
<p>The internet has a very specific picture of a Karen. She is middle-aged. She has an angular haircut. She is asking for the manager.</p>
<p>The data has a different picture. The typical living Karen is not 45. She is closer to 65. She is more likely to <em>be</em> a grandmother than to yell at one.</p>
<h2>The name was already old</h2>
<p>Karen was not born in the meme. It rose through the 1940s and 1950s, hit its highest birth count in 1957 — more than 40,000 baby girls in a single year — reached its highest rank, #3, in 1965, and has been falling ever since.</p>
<table>
<thead><tr><th>Era</th><th>Karen''s rank</th></tr></thead>
<tbody>
<tr><td>1957 (most births)</td><td>5</td></tr>
<tr><td>1965 (peak rank)</td><td>3</td></tr>
<tr><td>1970s</td><td>25</td></tr>
<tr><td>1980s</td><td>84</td></tr>
<tr><td>2000s</td><td>170</td></tr>
<tr><td>2019</td><td>662</td></tr>
<tr><td>2020</td><td>821</td></tr>
</tbody>
</table>
<p>There is a small puzzle hiding in that table: more Karens were born in 1957 (40,591) than in 1965 (32,869), yet the name ranked <em>higher</em> in 1965. The field was simply thinning around it — the giants of the early baby boom were fading faster than Karen was, so a smaller Karen climbed a shrinking ladder. Then it fell off the ladder entirely.</p>
<p>By the time the joke arrived, the name had already left the building. The decline did not start in 2020. The meme just stood next to a name that was half a century into a free fall and took the credit.</p>
<p>That is the difference between a name that is <em>unfashionable</em> and a name that is <em>dated</em>. Karen is dated. It points at a birth decade the way a rotary phone points at a kitchen wall.</p>
<h2>Counting the living, not the born</h2>
<p>Most baby-name sites can tell you how many Karens were <em>born</em>. We care about how many are <em>here</em>.</p>
<p>Every birth year gets run through an actuarial life table — the same kind insurers use — so we can estimate how many people with a given name are still alive, and how old they are. A name is not a chart. It is a crowd of living people, aging in real time.</p>
<p>Run Karen through that table and two facts fall out.</p>
<p>First, there are still a lot of them — by our estimate, about 775,000 living Americans named Karen. This is not a rare name. It is a common name attached almost entirely to one generation.</p>
<p>Second, and this is the whole story: the median living Karen is about 65 years old, and most are between 58 and 72. She was born around 1961, near the top of the wave. She is retiring — or already retired — not climbing a corporate ladder. Her own kids are grown.</p>
<p>The meme aged the name <em>down</em>. Reality is aging it <em>up</em>.</p>
<h2>There is no next Karen</h2>
<p>The part that makes Karen a NobodyNamed story, and not just a meme story, is what is happening at the bottom of the chart.</p>
<p>Almost no one is being named Karen anymore — just 175 newborns in 2025, down from more than 40,000 at the peak. The youngest Karens are already adults. There is no replacement generation filling in underneath — no nursery full of future Karens to lower the average age back down.</p>
<p>That is the signature of a name that has crossed from <em>declining</em> into <em>endangered</em>: a large living population with a high median age and a birth rate near zero. The crowd is real, but no one new is joining it, and the clock only runs one way.</p>
<p>Compare it with <a href="/name/Elizabeth/">Elizabeth</a>, a name that belongs to every decade at once and so belongs to none of them. Elizabeth has babies, teenagers, mothers, and grandmothers. Its median age sits in the middle of life because the name keeps getting refilled. Karen does not get refilled. Its median age climbs by roughly a year, every year, because the only thing happening to the population of Karens is that it is getting older.</p>
<h2>The joke and the obituary</h2>
<p>There is something quietly strange about the most mocked name of the 2020s being, demographically, one of the gentlest. The living Karens are overwhelmingly women in their late 50s, 60s, and early 70s. When they were having children, the names at the top of the charts were Jessica and Ashley. By then Karen already sounded like their mother''s generation.</p>
<p>The meme will fade. It may also have sped up something that was going to happen anyway. A handful of parents who might once have used the name — for a grandmother, for a tribute, for the sound of it — quietly crossed it off. The counts fit that story: 440 Karens born in 2019, 332 in 2020, then 229 in 2021 — nearly halved in two years, a small acceleration at the end of a long decline.</p>
<p>So: how many Karens are left? About 775,000, and the number falls a little every year — not because the name is being replaced, but because it isn''t.</p>
<p>The manager Karen demanded to speak to is turning 65 this year.</p>', 'published', 'NobodyNamed', '/api/og/default', '2026-09-27T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
