-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('how-america-stopped-sharing-names', 'How America Stopped Sharing Names', 'We abandoned our most popular names, quietly converged on a few sounds, then manufactured uniqueness by respelling them. A century of American individua...', '<p>Two facts about American names look like they cannot both be true.</p>
<p>The first: we stopped sharing them. In 1880, the ten most popular boys'' names covered <strong>44%</strong> of all newborn boys — nearly half a country drawing from one short list. Today the top ten cover <strong>8%</strong>. For girls the slide runs from 25% to 7%. The shared name, the name three kids in every classroom answered to, is gone.</p>
<figure class="nv-fig">
<div id="nv-conformity"></div>
<figcaption>Act I — the top-10 names'' share of all births, by sex, 1880–2025. The shared name collapses.</figcaption>
</figure>
<p>The second fact contradicts the first. Even as we fled the popular names, we <em>converged</em> on a smaller set of <strong>sounds</strong> — especially for boys. The single most common ending letter for a boy''s name accounted for about 15% of births for the whole first half of the 20th century. Then, starting in the 1960s, it climbed: by 2010 <strong>more than a third of all American boys</strong> got a name ending in the letter N — Aiden, Mason, Logan, Ethan, Jackson, Jaxon. Girls never moved off the vowel: about 37% have ended in a single dominant letter for 145 years, first the <strong>-E</strong> era (Annie, Carrie, Bessie), then the <strong>-A</strong> era (Linda, Lisa, Emma, Olivia).</p>
<figure class="nv-fig">
<div id="nv-sounds"></div>
<figcaption>Act II — share of births ending in the single most common ending letter. Boys converge on -N; girls never left the vowel.</figcaption>
</figure>
<p>So: fewer shared <em>names</em>, but fewer shared <em>sounds</em>. How can both be true at once?</p>
<h2>The reconciliation: we respell</h2>
<p>The answer is that American individuality stopped expressing itself through <em>choice of name</em> and started expressing itself through <strong>spelling</strong>. Parents take a sound everyone agrees on and write it a way no one else has. A 2010 nursery full of Jaydens, Aidens, Caydens, and Kaidens sounds identical at roll call and looks unique on every name tag. The originality is purely orthographic — and you can watch it detonate, the same explosion caught at three different stages.</p>
<p><strong>Caitlin</strong> is a complete supernova. Essentially nonexistent before the late 1970s, the sound <em>KATE-lin</em> splintered into Caitlin, Caitlyn, Katelyn, Kaitlyn, Katelynn, Katlyn and a dozen more, peaked at <strong>17 spellings</strong> in 1998, and is now nearly extinct in all of them — an entire lifecycle inside one generation.</p>
<p><strong>-aden</strong> barely existed before 1980. Then a sound that was effectively <em>invented</em> shattered into <strong>81 distinct spellings</strong> by 2012 — Jayden, Aiden, Brayden, out to Zaiden, Raiden, Khayden and Caedyn — more than 100,000 boys in a single year at its height. It is now collapsing: once a sound has eighty spellings, none of them feels special, and the whole family caves in.</p>
<figure class="nv-fig">
<div id="nv-spelling"></div>
<figcaption>Act III — distinct spellings (25+ babies/year) of one sound. Three families at three stages: dead, collapsing, and still cresting.</figcaption>
</figure>
<p><strong>-eigh</strong> is the one still running. And it works differently from the other two. Caitlin was one name; -aden was one sound; but <strong>-leigh</strong> is a <em>productive suffix</em> — a decorative ending you can bolt onto any root to mint a new daughter''s name on demand. Everleigh. Oakleigh. Wrenleigh. Emberleigh. Novaleigh. Riverleigh. It has become a morpheme that means, roughly, <em>a girl, bespoke.</em> And the letters do no work at all: Ryleigh is Riley, Charleigh is Charley, Hayleigh is Hailey. The "-eigh" is four silent letters of pure decoration. Here is a single year of it — every -eigh spelling given to at least 25 American girls in 2024, sized by how many:</p>
<figure class="nv-fig">
<div id="nv-eighwall"></div>
<figcaption>The live frontier: 73 ways to end a girl''s name in a silent "-eigh," 2024.</figcaption>
</figure>
<h2>What the supernova means</h2>
<p>Put the three charts together and the paradox dissolves. American individualism did not invent new names, and it did not even invent new sounds. It took a shrinking set of shared sounds and <strong>fragmented them across the page</strong> — Caitlin seventeen ways, Aiden eighty-one, Riley into Ryleigh into anything-leigh without limit. We did not get more creative. We got more creative with the same few letters.</p>
<p>And the supernova is self-consuming. The instant a sound accumulates enough spellings, the distinctiveness each one was bought for evaporates, and parents move to the next frontier. Caitlin''s generation has already burned out; -aden''s is burning now; -eigh''s is still bright. There will be another — there is always another — because the thing being chased was never a name. It was the feeling of being the only one.</p>
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="/assets/blog-sharing-names.js"></script>', 'draft', 'NobodyNamed', '/api/og/default', '2026-06-12T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
