-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('debut-of-the-year', 'Debut of the Year', 'The biggest baby-name debut of every year since 1910 — a century of American media history written in birth certificates, from a WWI marshal to Roots to...', '<p>Some names don''t fade in. They arrive — from nothing, at scale, in a single year — because something on a screen or a stage or a ballot put them there. If you take every name and ask which one <em>debuted</em> with the biggest splash in each year, you don''t get a list of names. You get a timeline of what America was watching.</p>
<p>Below is that almanac. For every year since 1910, the boy''s and girl''s name that appeared for the first time with the largest single-year count — the loudest debut. Flip between Boys and Girls, or filter to the ones with a clear cultural trigger. Each name is sized by how big its arrival was, and links to its full history.</p>
<div id="nv-debut"></div>
<h2>One event named a whole generation</h2>
<p>Read top to bottom, the eras change costume. The early decades belong to <strong>war heroes and headlines</strong> — <strong>Foch</strong> (1918) for the marshal who won the First World War, <strong>Mcarther</strong> for the general, <strong>Willkie</strong> for a presidential nominee, <strong>Rockne</strong> for a coach killed in a plane crash. Then come the <strong>TV cowboys</strong> — <strong>Maverick</strong>, <strong>Rowdy</strong>, <strong>Hoby</strong> — followed by the <strong>idols</strong> (<strong>Illya</strong> of <em>The Man from U.N.C.L.E.</em>) and the <strong>martyrs</strong> (<strong>Medgar</strong>, in the year Medgar Evers was killed).</p>
<p>But the single loudest moment in the whole record belongs to one television event. In 1977, <em>Roots</em> aired, and it produced the biggest debut of <strong>both</strong> sexes: <strong>Levar</strong> (523 boys, for LeVar Burton) and <strong>Kizzy</strong> (1,117 girls, for Kunta Kinte''s daughter). No other event in a century comes close — Kizzy is the largest single-year name debut on record, period.</p>
<h2>The girls'' side is louder — and more televised</h2>
<p>After about 1970 the debut engine runs almost entirely on Black and Latino popular culture, and the girls'' list is the more media-saturated of the two. TV heroines: <strong>Cinnamon</strong>, <strong>Fallon</strong>, <strong>Jaleesa</strong>, <strong>Moesha</strong>, <strong>Vanellope</strong>, <strong>Rey</strong>. R&amp;B and hip-hop: <strong>Sade</strong>, <strong>Erykah</strong>, <strong>Kelis</strong>, <strong>Kehlani</strong>, <strong>Zhavia</strong>, <strong>Pharrell</strong>, <strong>Jahseh</strong>. And a deep telenovela current that the boys'' side only hints at — <strong>Isamar</strong>, <strong>Yamilex</strong>, <strong>Greidys</strong>, <strong>Dalary</strong>. The boys lean a little more toward sports and rap; the girls toward television and divas. Both converge on the same truth: for fifty years, the names that arrive loudest have been the ones America''s screens taught it to love.</p>
<h2>A glitch crashes the party</h2>
<p>Two years are won not by a person but by a bug. In 1989 the biggest "debut" for boys is <strong>Christop</strong> and for girls <strong>Alexandr</strong> — Christopher and Alexandra with their final letters chopped off, a one-year data error in which a batch of names was truncated to eight characters. They''re flagged in red above. We left them in on purpose: a good almanac shows its seams, and the data''s own mistakes are part of its history too.</p>
<script src="/assets/blog-debut-of-the-year.js"></script>', 'draft', 'NobodyNamed', '/api/og/default', '2026-06-13T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
