-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('eithan-and-ailany', 'Eithan and Ailany Aren''t New Names', 'Eithan and Ailany are 2025''s fastest-rising names. Both are respellings of sounds America already had, arriving by the spelling instead of the name.', '<p>In 2023, 311 girls were named <a href="/name/Ailany/">Ailany</a>. In 2025, 7,136 were.</p>
<p><a href="/name/Eithan/">Eithan</a> went from 876 births in 2023 to 3,636 in 2025.</p>
<p>Both are among the fastest-rising names in the country. The Social Security Administration''s own 2025 report named them, almost: its top-5 fastest-risers listed <a href="/name/Ailanny/">Ailanny</a>, not Ailany, and <a href="/name/Neithan/">Neithan</a>, not Eithan. Same names, different spelling. SSA''s own list undercounted both.</p>
<h2>The name on the form isn''t the sound in the room</h2>
<p>Baby-name consultant Colleen Slagen, quoted in <a href="https://www.today.com/parents/babies/top-baby-names-2025-olivia-liam-rcna344252">TODAY''s coverage</a> of the SSA report, calls this "classic with a twist": parents want a sound everyone already recognizes, spelled a way no cousin, sibling, or classmate has it. Ethan becomes Eithan, or Neithan. A sound close to Ailani becomes Ailany, or Aylani, or Ailanny, or a dozen more.</p>
<p>That is the exact mechanism from <a href="/blog/how-america-stopped-sharing-names/">How America Stopped Sharing Names</a>: parents fragmenting one shared sound across many spellings. This is that mechanism caught in the newest year of data available, moving faster than it did for Caitlin or -aden.</p>
<h2>SSA counted one spelling each. There are at least twenty-five.</h2>
<p>Search the full name list for anything starting Ailan-, Aylan-, or Eylan-, and twenty-five distinct girls'' spellings turn up, from 7,136 births down to 5, all clearly the same name said out loud and written down twenty-five different ways.</p>
<div class="blog-visual">
  <h3>The six biggest spellings, 2025 births</h3>
  <div class="blog-bars">
    <div class="blog-bar-row"><span class="blog-bar-name">Ailany</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:100%; min-width:4px; background:#a6382a"></span></span><span class="blog-bar-value">7,136</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Ailani</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:25.3%; min-width:4px; background:#22745d"></span></span><span class="blog-bar-value">1,807</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Aylani</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:14.6%; min-width:4px; background:#465d75"></span></span><span class="blog-bar-value">1,043</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Ailanny</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:3.9%; min-width:4px; background:#9270a7"></span></span><span class="blog-bar-value">280</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Ailana</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:2.9%; min-width:4px; background:#a96720"></span></span><span class="blog-bar-value">205</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Aylany</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:1.9%; min-width:4px; background:#6b8e5a"></span></span><span class="blog-bar-value">133</span></div>
  </div>
</div>
<p>Add every spelling together and 11,022 American girls got some version of this name in 2025 alone. <a href="/name/Ailani/">Ailani</a> is the root: a real, moderately used name since the early 2000s, with its own two earlier pockets of popularity in California. The other twenty-four spellings are copies of its sound. <a href="/name/Ailany/">Ailany</a> is the outlier among them: 311 births in 2023, 7,136 in 2025, now about 65% of the entire family''s volume and the 14th most common girls'' name in the country. Ailani itself does not crack the top 100.</p>
<table>
<thead><tr><th>Spelling</th><th>2025 births</th></tr></thead>
<tbody>
<tr><td><a href="/name/Ailany/">Ailany</a></td><td>7,136</td></tr>
<tr><td><a href="/name/Ailani/">Ailani</a></td><td>1,807</td></tr>
<tr><td><a href="/name/Aylani/">Aylani</a></td><td>1,043</td></tr>
<tr><td><a href="/name/Ailanny/">Ailanny</a></td><td>280</td></tr>
<tr><td><a href="/name/Ailana/">Ailana</a></td><td>205</td></tr>
<tr><td><a href="/name/Aylany/">Aylany</a></td><td>133</td></tr>
<tr><td><a href="/name/Ailanys/">Ailanys</a></td><td>74</td></tr>
<tr><td><a href="/name/Aylana/">Aylana</a></td><td>52</td></tr>
<tr><td><a href="/name/Ailanni/">Ailanni</a></td><td>48</td></tr>
<tr><td><a href="/name/Aylanni/">Aylanni</a></td><td>45</td></tr>
<tr><td><a href="/name/Ailanie/">Ailanie</a></td><td>36</td></tr>
<tr><td><a href="/name/Aylanie/">Aylanie</a></td><td>27</td></tr>
<tr><td><a href="/name/Eylani/">Eylani</a></td><td>21</td></tr>
<tr><td><a href="/name/Ailanna/">Ailanna</a></td><td>20</td></tr>
<tr><td><a href="/name/Aylanis/">Aylanis</a></td><td>20</td></tr>
<tr><td><a href="/name/Ailanis/">Ailanis</a></td><td>17</td></tr>
<tr><td><a href="/name/Aylanna/">Aylanna</a></td><td>12</td></tr>
<tr><td><a href="/name/Ailannys/">Ailannys</a></td><td>7</td></tr>
<tr><td><a href="/name/Aylannie/">Aylannie</a></td><td>6</td></tr>
<tr><td><a href="/name/Ailanee/">Ailanee</a></td><td>6</td></tr>
<tr><td><a href="/name/Ailanii/">Ailanii</a></td><td>6</td></tr>
<tr><td><a href="/name/Aylanee/">Aylanee</a></td><td>6</td></tr>
<tr><td><a href="/name/Ailannie/">Ailannie</a></td><td>5</td></tr>
<tr><td><a href="/name/Aylanii/">Aylanii</a></td><td>5</td></tr>
<tr><td><a href="/name/Aylanny/">Aylanny</a></td><td>5</td></tr>
</tbody>
</table>
<p>The boys'' side is smaller but shaped the same way. <a href="/name/Eithan/">Eithan</a>, <a href="/name/Neithan/">Neithan</a>, and <a href="/name/Eitham/">Eitham</a> added up to 4,033 births in 2025. All three are respellings of Ethan. All three climb the SSA charts as if they were three different names.</p>
<h2>Nobody agrees on what it means, because nobody chose it for what it means</h2>
<p>Baby-name sites cannot settle on an origin for Ailany. Spanish, meaning "holy." Hebrew, by way of Eliana, meaning "God has answered." Hawaiian, by way of Ailani, meaning "chief" or "island." Three unrelated language families, three unrelated meanings, one name. That is not a name with a contested etymology. It is a name that was never chosen for its etymology at all. It was chosen for how it sounds, and the meaning got backfilled afterward by whoever wrote the baby-name-site entry.</p>
<h2>Where it''s happening</h2>
<p>Eithan and Ailany over-index by almost exactly the same amount in the same two states: Texas and California, both around double their expected share. Public name-and-ethnicity data puts Eithan at 52% Hispanic, the largest single group by a wide margin. Ailani, the older root name, shows the same pattern one state over: concentrated in California and Arizona rather than Texas, consistent with a name that took hold in Southwestern Hispanic naming culture years earlier and is only now producing a national wave of copies.</p>
<h2>The receipt</h2>
<p>Eithan and Neithan are two different spellings, filed as two different names, entered by two different sets of parents who very likely never spoke to each other. Their year-over-year growth:</p>
<table>
<thead><tr><th>Year</th><th>Eithan</th><th>Neithan</th></tr></thead>
<tbody>
<tr><td>2021</td><td>280</td><td>30</td></tr>
<tr><td>2022</td><td>605</td><td>43</td></tr>
<tr><td>2023</td><td>876</td><td>67</td></tr>
<tr><td>2024</td><td>1,599</td><td>137</td></tr>
<tr><td>2025</td><td>3,636</td><td>371</td></tr>
</tbody>
</table>
<p>Neither grew at a steady pace. Eithan''s worst year was +45%, Neithan''s best was +171%. But over the full four years, Eithan multiplied by about 13x and Neithan by about 12x, landing within 5% of each other despite never moving in the same increments in the same year. That is not two names having good years on their own schedules. That is one sound moving through the country, arriving on birth certificates spelled a dozen different ways, exactly the way <a href="/blog/how-america-stopped-sharing-names/">How America Stopped Sharing Names</a> said it would.</p>', 'published', 'NobodyNamed', '/api/og/default', '2026-09-21T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
