-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('jessica-extinction-event', 'The Jessica Extinction Event', 'In 1987, Jessica, Ashley, and Amanda accounted for 152,634 girls. In 2025, the same three names accounted for 2,854.', '<p>152,634 girls were named Jessica, Ashley, or Amanda in 1987.</p>
<p>In 2025, the same three names went to 2,854 girls.</p>
<p>Jessica was the #1 girls'' name in 1987, with Ashley at #2 and Amanda at #3. These were not marginal names. They were the sound of a school year.</p>
<p>By 2025, Jessica was down to 424 girls, Ashley to 1,829, and Amanda to 601.</p>
<p>More than 98% of the peak-year volume is gone.</p>
<div class="blog-visual">
  <h3>Peak year compared with 2025</h3>
  <div class="blog-bars">
    <div class="blog-bar-row"><span class="blog-bar-name">Jessica</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:0.8%; min-width:4px; background:#a6382a"></span></span><span class="blog-bar-value">55,992 peak -> 424 in 2025</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Ashley</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:3.3%; min-width:4px; background:#22745d"></span></span><span class="blog-bar-value">54,856 peak -> 1,829 in 2025</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Amanda</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:1.4%; min-width:4px; background:#465d75"></span></span><span class="blog-bar-value">41,786 peak -> 601 in 2025</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Brittany</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:0.7%; min-width:4px; background:#9270a7"></span></span><span class="blog-bar-value">37,792 peak -> 281 in 2025</span></div>
    <div class="blog-bar-row"><span class="blog-bar-name">Courtney</span><span class="blog-bar-track"><span class="blog-bar-fill" style="width:0.5%; min-width:4px; background:#a96720"></span></span><span class="blog-bar-value">15,380 peak -> 78 in 2025</span></div>
  </div>
</div>
<p>The names still sound recent to the people who grew up with them. That is part of the decline. Jessica does not sound like Mildred. Ashley does not sound like Bertha. Brittany does not sound like Ethel. These are people in group chats, payroll systems, school pickup lines, and neighborhood text threads.</p>
<p>Parents have not stopped recognizing the names. They recognize them too well.</p>
<h2>The 1987 list in 2025</h2>
<p>The top girls'' names from 1987 still read like a class roster: Jessica, Ashley, Amanda, Jennifer, Sarah, Stephanie, Brittany, Nicole, Heather, Elizabeth.</p>
<p>Only Elizabeth stayed near the top. It ranked #10 in 1987 and #17 in 2025. The other names took on a narrower age signature.</p>
<table>
<thead><tr><th>Name</th><th>Peak year</th><th>Peak births</th><th>2025 births</th><th>Peak left</th></tr></thead>
<tbody>
<tr><td>Jessica</td><td>1987</td><td>55,992</td><td>424</td><td>0.8%</td></tr>
<tr><td>Ashley</td><td>1987</td><td>54,856</td><td>1,829</td><td>3.3%</td></tr>
<tr><td>Amanda</td><td>1987</td><td>41,786</td><td>601</td><td>1.4%</td></tr>
<tr><td>Brittany</td><td>1989</td><td>37,792</td><td>281</td><td>0.7%</td></tr>
<tr><td>Jennifer</td><td>1972</td><td>63,600</td><td>501</td><td>0.8%</td></tr>
<tr><td>Heather</td><td>1975</td><td>24,301</td><td>177</td><td>0.7%</td></tr>
<tr><td>Tiffany</td><td>1988</td><td>18,364</td><td>304</td><td>1.7%</td></tr>
<tr><td>Courtney</td><td>1990</td><td>15,380</td><td>78</td><td>0.5%</td></tr>
<tr><td>Megan</td><td>1990</td><td>20,259</td><td>301</td><td>1.5%</td></tr>
</tbody>
</table>
<p>The dates matter. These names did not peak across a century. Most peaked between 1987 and 1990. The decline is clustered too.</p>
<p>The girls named Jessica and Ashley in 1987 turned 38 in 2025. Amanda turned 38 too. Brittany turned 36. Megan turned 35. Those are baby-naming ages, teacher ages, aunt ages, manager ages.</p>
<h2>Familiar in the wrong direction</h2>
<p>Parents often say they want a name that feels familiar but not common. Jessica became familiar because it was common. That familiarity now points backward.</p>
<p>The name arrives with people attached. Jessica is a cousin or a coworker. Ashley is a manager or a friend from college. Brittany is someone with old photos from 2009. Amanda is on a class email thread.</p>
<p>That is different from an old name. An old name can feel ready for reuse once enough living memory clears out. A saturated parent-generation name has the opposite problem. Too many people still carry it in daily life.</p>
<h2>Elizabeth is the control case</h2>
<p>Elizabeth shows the difference. In 1987, 18,608 girls were named Elizabeth. In 2025, 6,760 girls were named Elizabeth.</p>
<p>Elizabeth declined less. It ranked #10 in 1987 and #17 in 2025.</p>
<p>The name belongs to too many periods to get pinned to one graduating class. It is biblical, royal, colonial, Victorian, midcentury, and current. It also has a long nickname bench: Liz, Beth, Betsy, Libby, Eliza, Liza, Ellie.</p>
<p>Jessica does not have that range. Ashley does not either. Brittany has less. Those names point to a smaller window.</p>
<h2>The same risk is visible now</h2>
<p>The 2025 girls'' list starts Olivia, Charlotte, Emma, Amelia, Sophia, Mia, Isabella, Evelyn, Sofia, Eliana.</p>
<p>Some of those names will hold. Some will fall. The Jessica data shows the condition to watch: a name becomes risky when it is common enough to mark a cohort.</p>
<p>Olivia had 13,544 girls in 2025. Charlotte had 13,400. Emma had 12,754. Those counts are far below Jessica''s peak, but the pattern does not require a 55,000-birth year. It requires enough repetition for children to know the name as part of their peer group.</p>
<p>Jessica went from 55,992 girls in 1987 to 424 in 2025. Ashley went from 54,856 to 1,829. Amanda went from 41,786 to 601.</p>
<p>The names are still easy to recognize. They are rare again on birth certificates.</p>', 'published', 'NobodyNamed', '/api/og/default', '2026-05-24T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
