-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES ('press-start-to-name', 'Press Start to Name', 'Forty years of video games leaked onto real American birth certificates — often the exact year a game shipped. A character-select roster of every name t...', '<p>In January 2022, the game <em>Pokémon Legends: Arceus</em> shipped. That same year, for the first time in American history, the Social Security Administration recorded seven baby boys named <strong>Arceus</strong> — after the Pokémon universe''s literal creator-god. The name had never existed before. The release date <em>is</em> the birth date.</p>
<p>That''s the pattern, over and over: a character lands, and within a year the name lands too. Take every distinctive video-game name and check the birth records, and you get a roster of fandom leaking into the nursery. Pick a fighter.</p>
<div id="nv-pressstart"></div>
<h2>Final Fantasy is the MVP</h2>
<p>No franchise has minted more real names — and one is a beautiful deep cut. <strong>Aeris</strong> appears in 1998, right after Final Fantasy VII''s US release; <strong>Aerith</strong> — the <em>corrected</em> localization spelling — shows up later and surges with the 2020 Remake. The translation history of a single character is preserved in two separate waves of babies. Add <strong>Tidus</strong>, <strong>Auron</strong>, <strong>Rinoa</strong>, <strong>Noctis</strong>, <strong>Sephiroth</strong>, <strong>Tifa</strong>, and <strong>Vaan</strong>, each arriving within a year of its game.</p>
<h2>Named the year the game shipped</h2>
<p>The Arceus effect is everywhere once you look. <strong>Ezreal</strong> first appears in 2010, the year the League of Legends champion launched. <strong>Yennefer</strong> debuts in 2020, the year after Netflix''s <em>Witcher</em>. Assassin''s Creed even names one child per release — <strong>Altair</strong>, then <strong>Ezio</strong>, then <strong>Bayek</strong>, then <strong>Eivor</strong> — and Mortal Kombat coined <strong>Kitana</strong> and <strong>Mileena</strong> from nothing in 1994, dead-on the arcade-and-movie craze.</p>
<h2>The heavyweight: a game resurrected a flapper name</h2>
<p>The biggest name on the board isn''t a coinage — it''s a rescue. <strong>Zelda</strong> belonged to Zelda Fitzgerald and was nearly extinct by mid-century, then <em>Breath of the Wild</em> (2017) brought it to an all-time peak. A video game didn''t just add a name; it brought a 1920s one back from the dead.</p>
<h2>The impostors</h2>
<p>Honesty check: some names <em>look</em> like a gamer''s pick but aren''t. <strong>Mario</strong>, <strong>Dante</strong>, and <strong>Lara</strong> are older than their games; <strong>Jinx</strong> peaked in 1950, not with <em>Arcane</em>; <strong>Zidane</strong> is the footballer, not Final Fantasy IX. Hit "reveal" in the roster above to see the nine we benched, and why. The genuine tally — names truly summoned by a game — is smaller, stranger, and a lot more fun.</p>
<script src="/assets/blog-press-start.js"></script>', 'published', 'NobodyNamed', '/api/og/default', '2026-06-13T09:00:00.000Z', datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
