// REVIEWED EDITORIAL COPY: decade thesis drafts are checked against versioned
// payload evidence before commit. They are NOT generated at request time and
// must never be generated by an AI service at build or runtime (PROMPT §6, §17).
//
// STATUS (1980s): FINAL. Every figure below was re-checked against the real
// generated payload data/dist/decade-hub-1980.json (methodologyVersion
// decade-hub/v1.0.0, sourceVersion ssa-national-2025, built from live D1).
// Re-verify these figures whenever the payload is rebuilt on a newer vintage.

export interface DecadeThesis {
  heading: string;
  paragraphs: string[];
  sourceVersion: string;
  heroOrder?: "scorecard-lede-thesis" | "lede-thesis-scorecard";
  generationLink?: { href: string; label: string; targetId?: string; copy?: string };
}

export const DECADE_THESES: Record<string, DecadeThesis> = {
  "1880s": {
    sourceVersion: "ssa-national-2025",
    heading: "The old order, still tightly gathered",
    paragraphs: [
      "The 1880s profile covers 1880–1889 and contains 2,408,091 recorded births: 1,312,690 girls and 1,095,401 boys, across 3,951 distinct names. Mary is the girls’ popularity champion with 91,668 births in the decade; John leads the boys with 89,949. These are counts in the SSA file, not an estimate of every birth in the country.",
      "The decade is relatively concentrated: the ten largest name-and-sex combinations account for 22.25% of recorded births, and the top hundred account for 63.23%. Its diversity score is 70.8837, its effective number of names is 354.39, and its concentration score is 0.8325. Together those measures describe a large long tail beneath a comparatively narrow popular core; they do not say that families were making the same cultural choices for the same reasons.",
      "Popularity and ownership separate cleanly here. Maud is the leading girls’ ownership name, with 4,201 decade births out of 13,159 lifetime births, a 0.319249 decade share, and an ownership score of 88.2932; it ranks 74th in popularity. Will leads boys’ ownership with 6,196 decade births out of 45,952 lifetime births, a 0.134836 decade share, and an ownership score of 90.0176; it ranks 26th in popularity. The point is descriptive: a name can be relatively distinctive to an era without being its largest name.",
      "The representative classroom is drawn from 1884, the independent anchor year for this decade. It has 30 seats—16 girls and 14 boys—and all 30 names are unique: repeatedNames is 0, uniqueNames is 30, and the most repeated name has one seat. The displayed top-share value is 0.0333, the rounded form of one of thirty seats; this is a deterministic reconstruction, not a prediction about an actual classroom.",
      "No spelling family is approved for the 1880s. That is the honest editorial result rather than an invitation to merge historically distinct names just to create a large number. The records contain rare and ambiguous forms, but none has a manually reviewed family with at least two spellings above 1,000 births and at least 20,000 births combined.",
      "These are descriptive results from the SSA national files, with counts below five suppressed and sex recorded as the source’s binary reporting field rather than gender identity. The lifetime comparisons run through the 2025 data vintage, so ownership is a versioned descriptive score, not a claim that the 1880s caused a name’s later trajectory. The data cannot tell us why parents chose a name, and no paragraph here should be read as a causal account of nineteenth-century naming.",
    ],
  },
  "1890s": {
    sourceVersion: "ssa-national-2025",
    heading: "A broader roster beneath the familiar leaders",
    paragraphs: [
      "The 1890s cover 1890–1899 and contain 3,362,508 recorded births: 2,221,561 girls and 1,140,947 boys, across 5,022 distinct names. Mary remains the girls’ popularity champion with 131,138 births, while John leads boys with 80,664. The independent evidence file reproduces the same decade total and champion counts.",
      "The popular core is less concentrated than in the 1880s: the top ten account for 17.24% of births and the top hundred for 59.61%. The diversity score is 71.4206, the effective number of names is 439.73, and the concentration score is 0.6159. Those figures describe a broader distribution of recorded names alongside continuing high-volume leaders; they are not evidence of a particular social cause.",
      "Maude leads girls’ ownership with 11,304 births in the decade out of 45,754 lifetime births, a 0.247060 decade share, and an ownership score of 89.9841; its popularity rank is 53. Will leads boys’ ownership with 5,210 decade births out of 45,952 lifetime births, a 0.113379 decade share, and an ownership score of 89.3466; its popularity rank is 40. Mary and John win the raw popularity race, but the ownership score asks how strongly a name’s recorded lifetime clusters in this decade.",
      "The representative classroom uses 1894, with 20 girls’ seats and 10 boys’ seats. All 30 seats carry different names: uniqueNames is 30, repeatedNames is 0, and the most repeated name has one seat; the displayed top share is 0.0333. This is a fixed allocation from the 1894 distribution, not a claim that every real classroom had thirty different names.",
      "The strongest approved family is Catherine: Catherine (14,502), Katherine (9,408), Katharine (1,297), and Kathryn (5,653) combine to 30,860 births. Each is at least 1,000 births, the combined total clears 20,000, and the forms are defensible spelling variants of the Catherine/Katherine name rather than unrelated names. Sarah/Sara is also approved at 20,273 combined births. Cathryn is rejected from the family at 183 births because it fails the per-variant threshold, even though it is a plausible spelling variant.",
      "The SSA source is national but incomplete at the low-count edge: name-year counts below five are suppressed, and the file records sex rather than gender. Ownership and concentration are calculated against the current 2025 lifetime window and should be read as descriptive, versioned measures. The evidence shows association in recorded naming distributions, not why names rose or fell and not a causal story about the 1890s.",
    ],
  },
  "1900s": {
    sourceVersion: "ssa-national-2025",
    heading: "Expansion without a single new owner",
    paragraphs: [
      "The 1900s cover 1900–1909 and contain 4,285,123 recorded births: 2,927,552 girls and 1,357,571 boys, across 6,318 distinct names. Mary leads girls with 161,504 births and John leads boys with 84,590. The total reconciles exactly to the independent D1 anchor, which also reports Mary and John as the decade champions.",
      "The top ten account for 16.25% of births and the top hundred for 56.76%, while the diversity score is 71.1213, the effective number of names is 504.69, and the concentration score is 0.5532. The profile therefore has more distinct names and a larger effective roster than the two preceding decades, even while the leading names remain prominent. These metrics measure distributional shape, not the causes of that shape.",
      "Mabel is the girls’ ownership leader with 21,625 decade births out of 142,284 lifetime births, a 0.151985 decade share, and an ownership score of 91.6087; it ranks 30th in popularity. Will leads boys’ ownership with 3,246 decade births out of 45,952 lifetime births, a 0.070639 decade share, and an ownership score of 86.6070; it ranks 77th in popularity. The contrast with Mary and John shows why raw decade totals and decade ownership answer different questions.",
      "The representative classroom is based on 1904: 20 girls’ seats and 10 boys’ seats, with 30 unique names and zero repeated names. The most repeated name still has only one seat, and the stored top-share display is 0.0333. This reconstruction describes the deterministic classroom rule used by the profile; it does not generalize to every school or community.",
      "The strongest approved spelling family is Catherine: Catherine (22,006), Katherine (12,105), Katharine (1,246), and Kathryn (8,333) total 43,690 births. All four forms clear the 1,000-birth floor and the family clears 20,000; the forms are conventional spelling variants of the same name family. Sarah/Sara is also approved at 21,552 combined births. Cathryn is rejected from the Catherine family at 242 births because it fails the per-variant floor.",
      "The source is the SSA national birth-name file, not a complete census of names or identities; counts under five are suppressed, and the source reports sex rather than gender. Lifetime totals and ownership use the 2025 vintage, so the scores can change when the source vintage changes. Nothing in these associations establishes why the 1900s distribution looked this way or makes a causal claim about naming behavior.",
    ],
  },
  "1910s": {
    sourceVersion: "ssa-national-2025",
    heading: "A mass decade with a narrower effective core",
    paragraphs: [
      "The 1910s cover 1910–1919 and contain 14,831,446 recorded births: 8,156,259 girls and 6,675,187 boys, across 15,258 distinct names. Mary is the girls’ champion with 478,636 births; John is the boys’ champion with 376,311. The independent anchor agrees on the total and both champions, including their counts.",
      "Despite the much larger birth total, the distribution is more concentrated than the 1900s on the diversity measures: the top ten account for 18.02% and the top hundred for 54.54%; the diversity score is 66.1716, the effective number of names is 586.53, and the concentration score is 0.5703. The effective roster still grows in absolute terms because the decade is much larger, but the lower diversity score indicates a tighter distribution than the immediately preceding profile. This is a descriptive comparison, not an explanation.",
      "Lucile leads girls’ ownership with 11,738 decade births out of 34,887 lifetime births, a 0.336458 decade share, and an ownership score of 84.8093; it ranks 137th in popularity. Woodrow leads boys’ ownership with 18,355 decade births out of 39,107 lifetime births, a 0.469353 decade share, and an ownership score of 87.2872; it ranks 67th in popularity. Mary and John remain the popularity champions, while Lucile and Woodrow are the names whose recorded histories are more concentrated in the 1910s under this scoring system.",
      "The representative classroom uses 1914 and has 16 girls’ seats and 14 boys’ seats. It contains 30 unique names, with repeatedNames equal to 0 and the most repeated name at one seat; the stored top-share display is 0.0333. As elsewhere, this is an apportionment from one anchor year rather than a claim about the lived experience of every 1910s classroom.",
      "The strongest approved family is Catherine: Catherine (65,823), Katherine (36,884), Katharine (2,854), and Kathryn (29,235) combine to 134,796 births. The forms are semantically defensible spelling variants and each clears 1,000 births; the family is well above the 20,000 combined threshold. Other approved families also clear review—Elizabeth/Elisabeth totals 118,972, Marian/Marion 60,132, Eleanor/Elinor 58,173, and Sarah/Sara 53,529—but none is larger than Catherine. Cathryn is rejected at 981 births because it remains below the per-variant threshold.",
      "The SSA files suppress name-year counts below five and record sex rather than gender, so the long tail is necessarily understated and the category is not a complete account of identity. Ownership is calculated over recorded births through 2025 and is a descriptive concentration statistic, not evidence that a historical event caused a naming pattern. The profile can show what is present in the file; it cannot establish why the 1910s looked this way.",
    ],
  },
  "1920s": {
    sourceVersion: "ssa-national-2025",
    heroOrder: "scorecard-lede-thesis",
    generationLink: { href: "/millennial-names", label: "Millennial names", targetId: "editorial:millennial-names", copy: "the classroom names of the 1980s and 1990s" },
    heading: "A concentrated decade, and a wider story",
    paragraphs: [
      "The 1920s include 22,972,053 births recorded in the Social Security data: 11,952,683 girls and 11,019,370 boys across 18,108 name-and-sex records. Mary led girls with 701,755 births, while Robert led boys with 576,374. The ten largest name-and-sex combinations accounted for 19.03% of all recorded births, and the top hundred accounted for 54.58%.",
      "Those shares describe popularity, but they do not show which names belong most distinctly to the era. A long-running classic can be enormous in one decade while spreading most of its history across many others. Ownership asks a narrower question: how concentrated was a name's recorded lifetime inside these ten years, after smoothing rare names and accounting for prominence?",
      "By that measure, Dorothy leads the girls' ownership ranking. It was also the decade's second-most-popular girls' name, but its 368,875 births cluster more tightly around this era than Mary's much longer history. Seymour leads the boys' ownership ranking despite ranking 211th by 1920s births. The result is a reminder that identity and size are related, but not interchangeable.",
      "The representative classroom turns the national distribution into a fixed roster. Thirty seats apportioned from 1924 records produce sixteen girls and fourteen boys. In this deterministic reconstruction all thirty seats carry different names: even a concentrated naming pool does not make a duplicate inevitable at this classroom size.",
      "Spelling also changes the view. Conventional tables rank Katherine and Catherine separately. The manually reviewed family combines 121,626 recorded girls' births in the decade, a footprint large enough to sit near the top of the decade even though neither spelling tells the whole story alone.",
      "These figures describe the SSA's national files, not every birth or every person's identity. The files omit name-and-sex counts below five, record sex rather than gender, and do not explain why parents chose a name. Ownership is a versioned descriptive score—not a claim of cultural truth—and the methodology page publishes every formula and threshold behind it.",
    ],
  },
  "1930s": {
    sourceVersion: "ssa-national-2025",
    heading: "Familiar champions, era-specific ownership",
    paragraphs: [
      "The 1930s cover 1930–1939 and contain 21,229,562 recorded births: 10,663,028 girls and 10,566,534 boys, across 15,662 distinct names. Mary leads girls with 573,000 births, while Robert leads boys with 590,810. The independent D1 anchor matches the total and both champion identities and counts.",
      "The top ten account for 19.46% of recorded births and the top hundred for 55.20%. The diversity score is 65.2624, the effective number of names is 546.58, and the concentration score is 0.6166. In this profile the national total is large, but the effective roster is smaller than in the 1910s and the distribution is relatively concentrated; those are measurements of the recorded name distribution, not proof of a historical cause.",
      "Joan leads girls’ ownership with 173,439 decade births out of 481,238 lifetime births, a 0.360402 decade share, and an ownership score of 94.5012; it ranks seventh in popularity. Dick leads boys’ ownership with 10,163 decade births out of 29,273 lifetime births, a 0.347180 decade share, and an ownership score of 83.3452; it ranks 150th in popularity. Mary and Robert are the raw popularity champions, while Joan and Dick are more era-concentrated according to the ownership calculation.",
      "The representative classroom is drawn from 1934 and splits evenly into 15 girls’ seats and 15 boys’ seats. All 30 names are unique, repeatedNames is 0, and the most repeated name has one seat; the stored top-share display is 0.0333. It is a deterministic classroom reconstruction from the anchor-year distribution, not a claim that every 1930s classroom had the same roster.",
      "The strongest approved family is Catherine: Catherine (50,027), Katherine (25,193), Katharine (1,724), and Kathryn (22,583) combine to 99,527 births. Each spelling clears 1,000 births and the combined family clears 20,000; the variants are defensible spellings of the same name family. Elizabeth/Elisabeth is a close second at 97,764, while Marian/Marion totals 53,472, Eleanor/Elinor 50,141, and Sarah/Sara 54,774. Cathryn is rejected from the Catherine family at 798 births because it fails the per-variant floor.",
      "These figures come from SSA’s national files, which suppress counts below five and record sex rather than gender; they do not include every birth or explain personal identity. The lifetime window ends at the 2025 source vintage, making ownership a revisable descriptive score rather than a timeless cultural verdict. The data support comparisons in the recorded series, not causal claims about the Depression, media, migration, or any other historical explanation.",
    ],
  },
  "1940s": {
    sourceVersion: "ssa-national-2025",
    heading: "Familiar anchors, sharper era signatures",
    paragraphs: [
      "The 1940s contain 29,371,705 births in the Social Security national data: 14,484,843 girls and 14,886,862 boys, across 16,297 distinct recorded names. Mary was the girls' champion with 640,080 births, while James led the boys with 795,775.",
      "Popularity was still concentrated, but the long tail was substantial. The ten largest name-and-sex combinations accounted for 19.52% of recorded births and the top 100 for 58.43%; the diversity score was 63.74 out of 100, with 483.77 effective names. In other words, a relatively small upper tier carried much of the decade while thousands of other recorded names remained in circulation.",
      "Popularity and ownership are different measurements. Judith led the girls' ownership ranking with 218,037 births, 47.95% of her recorded lifetime in the decade, a popularity rank of 9, and an ownership score of 95.44. Larry led the boys' ownership ranking with 255,908 births, 31.69% of his lifetime in the decade, a popularity rank of 11, and an ownership score of 95.55: both names were large, but their era concentration—not just their totals—made them especially 1940s names.",
      "The representative 1944 classroom has fifteen girls' seats and fifteen boys' seats. All 30 seats carry different names, with zero repeated names and a top seat share of 3.33%; Barbara is the deterministic tie-break for “most repeated,” but it still receives only one seat. At this classroom size, the national distribution does not make a duplicate inevitable.",
      "The strongest reviewed spelling family is Steven: Steven and Stephen combine for 188,016 births (81,204 and 106,812 respectively), and both variants comfortably clear the decade threshold. A narrower Jeffrey/Jeffery family totals 39,094 births; Geoffrey remains outside that grouping because it is treated as a distinct traditional name rather than a direct spelling variant.",
      "These figures describe the SSA's national files for 1940 through 1949, not every birth or every person's identity. The files suppress name-year counts below five, record sex rather than gender, and do not explain why parents chose a name. Ownership is a versioned descriptive score about recorded birth concentration; it is not a causal claim about wartime culture, celebrity, religion, or any other reason a name may have been chosen.",
    ],
  },
  "1950s": {
    sourceVersion: "ssa-national-2025",
    heading: "The decade that Debra and Steven made legible",
    paragraphs: [
      "The 1950s contain 39,451,567 births in the Social Security national data: 19,234,406 girls and 20,217,161 boys, across 18,988 distinct recorded names. Mary remained the girls' champion with 625,606 births, while James led the boys with 843,768.",
      "The decade spread more of its births beyond the very top than the 1940s did. The top ten name-and-sex combinations accounted for 17.38% of births and the top 100 for 56.56%; the diversity score was 63.60 out of 100, with 526.13 effective names. The lower top shares and larger effective-name count point to a broader distribution than the preceding decade, even though the upper tier still mattered.",
      "Ownership surfaces names that raw popularity alone can miss. Debra led the girls' ownership ranking with 341,348 births, 61.98% of her lifetime in the decade, popularity rank 7, and ownership score 97.24. Kim led the boys' ownership ranking with only 21,208 births, 60.68% of his lifetime in the decade, popularity rank 146, and ownership score 85.13; that gap is the point of the measure, distinguishing a name's size from its decade-specific footprint.",
      "The representative 1954 classroom has fifteen girls' seats and fifteen boys' seats. Its 30 seats contain 30 unique names, zero repeated names, and a 3.33% top seat share; Barbara is listed as the most repeated name only because every name ties at one seat. The reconstruction therefore shows a varied classroom even inside a decade with highly recognizable national champions.",
      "The strongest reviewed spelling family is Steven: Steven and Stephen combine for 540,942 births (333,666 and 207,276), making the split spelling pattern much larger than either label alone. Jeffrey and Jeffery form a separate reviewed pair totaling 230,547 births; Geoffrey remains outside that family as a distinct traditional name.",
      "These figures describe the SSA's national files for 1950 through 1959, with lifetimes calculated through the 2025 data vintage. Counts below five in a name-year are suppressed, the source records sex rather than gender, and the data contains no explanation of parental intent. The decade and ownership language should remain descriptive: the figures show association and concentration in the recorded files, not what caused 1950s naming choices.",
    ],
  },
  "1960s": {
    sourceVersion: "ssa-national-2025",
    heading: "A mass favorite meets a wider roster",
    paragraphs: [
      "The 1960s contain 37,527,873 births in the Social Security national data: 18,265,222 girls and 19,262,651 boys, across 22,174 distinct recorded names. Lisa led the girls with 496,987 births, and Michael led the boys with 833,092.",
      "The decade's naming pool was less concentrated than the 1950s. The top ten name-and-sex combinations accounted for 15.20% of births and the top 100 for 52.71%; the diversity score reached 64.83 out of 100, with 656.45 effective names. The falling top shares and rising effective-name count show a roster broadening even while a few names remained nationally dominant.",
      "The 1960s show both sides of the popularity-versus-ownership distinction. Lisa was simultaneously the girls' popularity leader and ownership leader: 496,987 births, 51.38% of her recorded lifetime in the decade, popularity rank 1, and ownership score 95.76. For boys, Jeff led ownership with 62,072 births, 51.62% of his lifetime in the decade, popularity rank 54, and ownership score 89.46, while Michael's much larger 833,092-birth total made him the popularity champion; era fit and raw volume are not interchangeable.",
      "The representative 1964 classroom has fifteen girls' seats and fifteen boys' seats. Every one of its 30 seats has a different name, with zero repeated names and a 3.33% top seat share; Cynthia is the one-seat tie-break for most repeated. Even with Lisa and Michael at the top nationally, this fixed 30-seat reconstruction does not force a duplicate.",
      "The strongest reviewed spelling family is Steven: Steven and Stephen combine for 442,847 births (290,607 and 152,240). Jeffrey and Jeffery form another reviewed pair with 381,563 births; Geoffrey remains outside that family because it is treated as a distinct name rather than a direct spelling variant.",
      "These are descriptive results from SSA national birth records for 1960 through 1969, using the 2025 source vintage for lifetime measures. The source omits name-year counts below five, records sex rather than gender, and cannot identify the social mechanisms behind a trend. A high ownership score means recorded lifetime concentration in this decade under the published formula; it does not establish that television, music, politics, or any other proposed influence caused the pattern.",
    ],
  },
  "1970s": {
    sourceVersion: "ssa-national-2025",
    heading: "The long tail opens up",
    paragraphs: [
      "The 1970s contain 31,968,373 births in the Social Security national data: 15,452,212 girls and 16,516,161 boys, across 31,789 distinct recorded names. Jennifer was the girls' champion with 581,729 births, while Michael led the boys with 707,327.",
      "Among these four decades, the 1970s have the broadest recorded roster and the lowest concentration by top-share measures. The top ten name-and-sex combinations accounted for 14.15% of births and the top 100 for 48.85%; the diversity score was 65.56 out of 100, with 894.61 effective names. Less than half of the decade's births sit inside the top 100, a materially wider spread than the 1940s' 58.43%.",
      "Ownership makes the decade's contrasts especially visible. Katina led the girls' ownership ranking with only 7,888 births, 69.77% of her recorded lifetime in the decade, popularity rank 315, and ownership score 79.50. Jason led the boys' ownership ranking with 462,709 births, 43.98% of his lifetime in the decade, popularity rank 3, and ownership score 93.88; one is a narrowly era-shaped name and the other is both prominent and strongly concentrated in the decade.",
      "The representative 1974 classroom has fourteen girls' seats and sixteen boys' seats. It contains 30 unique names, zero repeated names, and a 3.33% top seat share; Amy is the deterministic one-seat tie-break for most repeated. The roster's variety is consistent with the decade's lower top-100 share, while remaining a fixed reconstruction rather than a survey of an actual classroom.",
      "The strongest reviewed spelling family is Brian: Brian and Bryan combine for 393,998 births (322,660 and 71,338). Jeffrey and Jeffery form a narrower 247,415-birth pair, while Sean, Shawn, and Shaun form a three-spelling family with 208,926 births. Geoffrey remains outside the Jeffrey grouping as a distinct traditional name.",
      "These figures come from SSA national records for 1970 through 1979 and inherit the source's suppression of name-year counts below five and its sex-at-birth classification rather than a gender measure. They cannot tell us why a name rose, fell, or clustered, and they do not measure every naming practice or identity. Ownership and diversity are descriptive statistics under a stated method, not causal explanations of the cultural history of the 1970s.",
    ],
  },
  "1980s": {
    sourceVersion: "ssa-national-2025",
    heroOrder: "lede-thesis-scorecard",
    generationLink: { href: "/millennial-names", label: "Millennial names", targetId: "editorial:millennial-names", copy: "the classroom names of the 1980s and 1990s" },
    heading: "A hundred names for half the decade",
    paragraphs: [
      "The 1980s include 35,634,486 American births in the Social Security data, with 17,175,557 girls and 18,458,929 boys, across 38,615 recorded names. Michael led the boys with 663,807 births. Jessica led the girls with 469,510. The ten most popular name-and-sex combinations accounted for 12.48% of all recorded births, and the top 100 accounted for 49.91%. Roughly half the decade's children carried one of a hundred names.",

      "The other half spreads thin. The 1980s have a diversity score of 65.27 out of 100, and the effective number of names, the size an equally common roster would need to produce the same spread, is about 986.",

      "Popularity and ownership are different measurements. Michael was massive in the 1980s, but he had been massive for a long time already. The names that belong most clearly to the decade are the ones whose recorded lifetimes cluster inside those ten years. By the ownership score on this page, the most 1980s girl's name is Krystle, which ranks only 242nd by popularity. The most 1980s boy's name is Dustin, ranked 44th. The score measures how much of a name's recorded lifetime falls inside the decade, with a penalty for rare names so they cannot win on a technicality.",

      "A second pattern runs the other direction. William, Charles, and Mary all rank near the top for the decade, but they fall into the popular-but-timeless group. They were used heavily in the 1980s, yet their recorded histories are spread so evenly that no single decade owns them.",

      "The classroom example makes that easier to picture. Rebuild an average 30-student class of 1984 births from the national records, and no name is common enough to guarantee a duplicate. All 30 seats have different names. Even Michael has an expected seat count of just 0.60 across the 16 boys' seats. It only claims a seat in the reconstruction because of the leftover fraction.",

      "Spelling families tell a different story. Standard rankings count each spelling separately, so a name split across variants looks smaller than the whole pattern. Ashley alone ranks fourth among girls' names of the decade. Grouped with its five reviewed variants, the Ashley family totals 387,668 births, enough to rank third.",

      "Everything on this page comes from Social Security Administration birth records for 1980 through 1989, with lifetimes computed through 2025, the current data vintage. The source has limits. It records sex at birth rather than gender, and it suppresses any name-year count below five, so the rarest names are missing entirely. The methodology page covers both. The ownership score is a descriptive statistic about recorded births, not a judgment about what any name meant to the people who carried it.",
    ],
  },
  "1990s": {
    sourceVersion: "ssa-national-2025",
    heading: "The last mass-appeal decade before the long tail",
    paragraphs: [
      "The 1990s are complete in the SSA-national-2025 profile: 1990–1999 contains 37,485,138 recorded births, including 18,005,347 girls and 19,479,791 boys, across 50,448 distinct recorded names. Jessica led girls with 303,136 births, while Michael led boys with 462,466.",
      "The decade's diversity score is 67.733, with an effective number of names of 1,532.41 and a concentration score of 0.2395. The ten largest name-and-sex combinations account for 8.6104% of births, and the top 100 account for 40.7226%, so the most visible names are a minority of the decade even when they feel culturally ubiquitous.",
      "Brittany is the strongest female ownership story: it ranks seventh by 1990s popularity but first on the ownership measure, with 190,826 births and 52.9083% of its recorded lifetime in the decade. Tevin leads male ownership despite ranking only 316th by popularity, with 8,525 births and 72.7575% of its lifetime in the decade. By contrast, David, James, and John appear in the popular-but-timeless set at popularity ranks 12, 13, and 15 while their ownership ranks are 231, 285, and 288. Popularity measures size; ownership measures how distinctly a name belongs to an era.",
      "The deterministic classroom is drawn from 1994, a year with 3,717,784 births in the independent D1 check. Thirty seats resolve to fourteen girls and sixteen boys; all thirty seats have different names, and the repeated-name count is zero. Amanda is the most repeated roster name only in the formal sense of a one-seat tie, and the largest name share is 3.33%.",
      "The strongest straightforward family is Ashley: Ashley (301,820), Ashlee (15,978), Ashleigh (13,195), Ashlie (3,651), Ashly (3,216), and Ashli (2,169) combine to 340,029 births. These are reviewed spelling variants of the same late-century favorite, not a claim that the people behind the spellings had identical identities; every listed spelling clears the 1,000-birth threshold and the family clears 20,000.",
      "These are descriptive counts from the SSA national birth files, not a census of every birth or a complete account of naming practice. The files suppress name-year counts below five, record sex rather than gender, and do not explain why parents chose a name. The ownership score is a versioned descriptive statistic, and the spelling families are editorial groupings; none of these measures establishes a cause for the decade's naming patterns.",
    ],
  },
  "2000s": {
    sourceVersion: "ssa-national-2025",
    heading: "A softer center, with spelling doing more work",
    paragraphs: [
      "The complete 2000–2009 profile contains 38,437,096 recorded births: 18,476,657 girls and 19,960,439 boys, across 60,404 distinct recorded names. Emily led girls with 223,768 births, and Jacob led boys with 274,077.",
      "The 2000s have a diversity score of 70.9224, an effective number of names of 2,459.49, and a concentration score of 0.1456. The top ten name-and-sex combinations account for 5.7470% of births and the top 100 account for 31.7981%. The center of the distribution is therefore less concentrated than a simple memory of the decade's biggest names might suggest.",
      "Jaden leads female ownership with an ownership score of 80.49, even though it ranks 307th by popularity; 10,360 births place 76.2325% of its recorded lifetime inside the decade. Aidan leads male ownership with a score of 92.79, 76,513 births, and a 64.6056% decade share, while ranking 55th by popularity. Michael, Daniel, and Christopher illustrate the opposite pattern: they rank second, fifth, and sixth in popularity but belong to the popular-but-timeless group rather than owning the decade.",
      "The representative classroom uses 2004, which has 3,821,229 births in the independent D1 anchor. It contains fourteen girls and sixteen boys, with thirty unique names and zero repeated names across thirty seats. Abigail is the formal most-repeated name at one seat, and the top roster share is 3.33%; a famous top name is not the same thing as a guaranteed duplicate in a small class.",
      "The clearest family is Aiden: Aiden (83,554), Aidan (76,513), Ayden (26,295), and Aden (9,677) combine to 196,039 births. These are common spelling forms of the same Aiden/Aidan sound pattern and each clears 1,000 births in the actual decade coverage. The grouping is an editorial way to show a pattern split across conventional tables, not an assertion that every bearer experienced the spellings as interchangeable.",
      "The figures describe the SSA's national files for 2000–2009; they do not represent all births, all communities, or every naming decision. Counts below five per name-year are suppressed, the source records sex rather than gender, and lifetime comparisons run only through the 2025 source vintage. Ownership and spelling-family totals are descriptive, not causal explanations of why names rose, fell, or accumulated creative spellings.",
    ],
  },
  "2010s": {
    sourceVersion: "ssa-national-2025",
    heading: "The decade of distributed favorites",
    paragraphs: [
      "The complete 2010–2019 profile contains 36,304,973 recorded births: 17,501,836 girls and 18,803,137 boys, across 60,123 distinct recorded names. Emma led girls with 195,070 births, while Noah led boys with 183,378.",
      "Diversity rises to 73.1153, with an effective number of names of 3,120.38 and a concentration score of 0.1092. The top ten combinations account for 4.7539% of births and the top 100 account for 26.7478%. That combination of a high diversity score and a smaller top-name share describes a decade whose recognizable favorites sit inside a broad naming field.",
      "Harper leads female ownership with an ownership score of 89.61, 85,193 births, and 61.2622% of its recorded lifetime in the decade; it ranks 16th by popularity. Bentley leads male ownership with a score of 90.90, 43,956 births, and a 73.2270% decade share, despite ranking 92nd by popularity. William, Michael, and James are popular-but-timeless examples at popularity ranks 4, 7, and 9, showing why a large count alone cannot identify the name most characteristic of an era.",
      "The classroom year is 2014, with 3,707,226 births in the independent check. Its thirty seats divide into fourteen girls and sixteen boys, all with different names; the repeated-name count is zero and the largest roster share is 3.33%. Abigail is the formal most-repeated name at one seat, so even a roster built from a high-volume year need not produce duplicates at this size.",
      "Sophia is the strongest clean family: Sophia (181,174) and Sofia (82,402) combine to 263,576 births. The two spellings are established alternatives of the same name and both far exceed the minimum threshold. The combined figure makes visible a pattern that separate rankings would divide without pretending that a spelling family is an SSA category or a statement about individual identity.",
      "This is a descriptive view of the SSA national files for 2010–2019, with rare name-year counts below five omitted and sex recorded rather than gender. It cannot tell us whether media, geography, migration, religion, economics, or any other factor caused a name's trajectory. Ownership is a versioned concentration measure, and the family grouping is a reviewed editorial lens rather than a causal or demographic conclusion.",
    ],
  },
  "2020s": {
    sourceVersion: "ssa-national-2025",
    heading: "A partial decade already widening",
    paragraphs: [
      "The 2020s profile is explicitly partial: it covers 2020–2025 only and is not complete. That six-year window contains 20,092,648 recorded births, including 9,729,572 girls and 10,363,076 boys, across 49,950 distinct recorded names. Olivia led girls with 95,853 births, and Liam led boys with 124,842; none of these figures should be projected to a ten-year total.",
      "Within the 2020–2025 window, the diversity score is 75.3979, the effective number of names is 3,488.16, and the concentration score is 0.0919. The top ten combinations account for 4.4054% of births and the top 100 account for 23.7393%. These are provisional partial-window measures, but they already describe a broad distribution rather than a decade dominated by a few names.",
      "Ailany leads female ownership with a score of 83.78, 10,548 births, and 94.5161% of its recorded lifetime in the six-year window, while ranking 167th by popularity. Thiago leads male ownership with a score of 84.50, 24,140 births, and a 68.5795% window share, while ranking 87th. The popular-but-timeless group still includes James and William at popularity ranks 4 and 6, but ownership comparisons here are especially provisional because only six years of the decade are observed and the current source ends in 2025.",
      "The classroom year is 2024, with 3,343,078 births in the independent D1 check. The thirty-seat reconstruction divides evenly into fifteen girls and fifteen boys, with thirty unique names and zero repeats; Amelia is the formal most-repeated name at one seat, and the top share is 3.33%. This is a snapshot from one observed year, not a forecast of the completed 2020s.",
      "Sophia is the strongest defensible family in the partial window: Sophia (74,758) and Sofia (45,288) combine to 120,046 births. Both spellings are well above the threshold and are conventional alternatives of the same name. The combined total is useful as an editorial view of split popularity, but it should remain labeled as a 2020–2025 result until later SSA vintages extend the coverage.",
      "The partial window is the central limitation: the SSA data currently reach 2025, so the profile cannot describe births in 2026–2029 or claim a finished decade. As elsewhere, counts below five per name-year are suppressed, the source records sex rather than gender, and the data do not explain why parents chose names. The ownership scores, family totals, and apparent widening are descriptive observations, not causal claims or predictions.",
    ],
  },
};
