// HAND-EDITED: decade thesis drafts. This copy is written and reviewed by a
// human editor; it is NOT generated at request time and must never be
// generated by an AI service at build or runtime (PROMPT §6, §17).
//
// STATUS (1980s): FINAL. Every figure below was re-checked against the real
// generated payload data/dist/decade-hub-1980.json (methodologyVersion
// decade-hub/v1.0.0, sourceVersion ssa-national-2017) in Stage 4.

export interface DecadeThesis {
  heading: string;
  paragraphs: string[];
}

export const DECADE_THESES: Record<string, DecadeThesis> = {
  "1980s": {
    heading: "A hundred names for half the decade",
    paragraphs: [
      "The 1980s recorded 35,627,408 American births in the Social Security data — 17,171,969 girls and 18,455,439 boys — spread across 38,588 distinct recorded names. Two names towered over the rest: Michael for boys, with 663,690 births across the decade, and Jessica for girls, with 469,472. The ten most popular name-and-sex combinations absorbed 12.48% of all recorded births, and the top one hundred accounted for 49.92% — half the decade's children carried one of a hundred names.",

      "Yet even inside its own ten years, the decade's births spread far beyond its biggest names. The diversity score for the 1980s is 65.27 out of 100, and the effective number of names — the size an equally common roster would need to produce the same spread — is about 986. Popularity and identity are also different measurements. Michael was enormous in the 1980s, but Michael had been enormous for decades. The names that most belong to the decade are the ones whose recorded lifetimes concentrate inside these ten years. By the ownership score on this page, the most 1980s girl's name is Krystle — only the 242nd most popular girl's name of the decade — and the most 1980s boy's name is Dustin, 44th by popularity. The score measures the share of a name's recorded lifetime that fell within the decade, adjusted so rare names cannot win on a technicality.",

      "The opposite pattern exists too. John, William, and Mary all rank among the decade's most popular names while landing in the popular-but-timeless view: heavily used in the 1980s, but spread so evenly across their recorded histories that no single decade owns them.",

      "The representative classroom makes the distribution concrete. Rebuild an average 30-student class of 1984 births from the national records and a quiet fact emerges: no name was common enough to guarantee a duplicate. All 30 seats carry different names. Even Michael, the decade's biggest name, has an expected seat count of just 0.60 across the 16 boys' seats — enough to claim one seat in the reconstruction only on the strength of its remainder.",

      "Spelling families show a different kind of understatement. Conventional rankings count each spelling separately, so a name split across popular variants looks smaller than the combined phenomenon. Ashley alone ranks fourth among girls' names of the decade; grouped with its five reviewed variants, the Ashley family totals 387,653 births — enough to rank third. Everything on this page derives from Social Security Administration birth records for 1980 through 1989, with lifetimes computed through 2017, the current data vintage. The source still has limits — it records sex at birth and suppresses counts below five — and the methodology page states each one. The ownership score is a descriptive statistic about recorded births, not a verdict about what any name meant to the people who carried it.",
    ],
  },
};
