// HAND-EDITED: decade thesis drafts. This copy is written and reviewed by a
// human editor; it is NOT generated at request time and must never be
// generated by an AI service at build or runtime (PROMPT §6, §17).
//
// STATUS (1980s): FINAL. Every figure below was re-checked against the real
// generated payload data/dist/decade-hub-1980.json (methodologyVersion
// decade-hub/v1.0.0, sourceVersion ssa-national-2025, built from live D1).
// Re-verify these figures whenever the payload is rebuilt on a newer vintage.

export interface DecadeThesis {
  heading: string;
  paragraphs: string[];
}

export const DECADE_THESES: Record<string, DecadeThesis> = {
  "1920s": {
    heading: "A concentrated decade, and a wider story",
    paragraphs: [
      "The 1920s include 22,972,053 births recorded in the Social Security data: 11,952,683 girls and 11,019,370 boys across 18,108 name-and-sex records. Mary led girls with 701,755 births, while Robert led boys with 576,374. The ten largest name-and-sex combinations accounted for 19.03% of all recorded births, and the top hundred accounted for 54.58%.",
      "Those shares describe popularity, but they do not show which names belong most distinctly to the era. A long-running classic can be enormous in one decade while spreading most of its history across many others. Ownership asks a narrower question: how concentrated was a name's recorded lifetime inside these ten years, after smoothing rare names and accounting for prominence?",
      "By that measure, Dorothy leads the girls' ownership ranking. It was also the decade's second-most-popular girls' name, but its 368,875 births cluster more tightly around this era than Mary's much longer history. Seymour leads the boys' ownership ranking despite ranking 211th by 1920s births. The result is a reminder that identity and size are related, but not interchangeable.",
      "The representative classroom turns the national distribution into a fixed roster. Thirty seats apportioned from 1924 records produce sixteen girls and fourteen boys. In this deterministic reconstruction all thirty seats carry different names: even a concentrated naming pool does not make a duplicate inevitable at this classroom size.",
      "Spelling also changes the view. Conventional tables rank Katherine and Catherine separately. The manually reviewed family combines 121,626 recorded girls' births in the decade, a footprint large enough to sit near the top of the decade even though neither spelling tells the whole story alone.",
      "These figures describe the SSA's national files, not every birth or every person's identity. The files omit name-and-sex counts below five, record sex rather than gender, and do not explain why parents chose a name. Ownership is a versioned descriptive score—not a claim of cultural truth—and the methodology page publishes every formula and threshold behind it.",
    ],
  },
  "1980s": {
    heading: "A hundred names for half the decade",
    paragraphs: [
      "The 1980s include 35,634,486 American births in the Social Security data, with 17,175,557 girls and 18,458,929 boys, across 38,615 recorded names. Michael led the boys with 663,807 births. Jessica led the girls with 469,510. The ten most popular name-and-sex combinations accounted for 12.48% of all recorded births, and the top 100 accounted for 49.91%. Roughly half the decade's children carried one of a hundred names.",

      "The other half spreads thin. The 1980s have a diversity score of 65.27 out of 100, and the effective number of names, the size an equally common roster would need to produce the same spread, is about 986.",

      "Popularity and ownership are different measurements. Michael was massive in the 1980s, but he had been massive for a long time already. The names that belong most clearly to the decade are the ones whose recorded lifetimes cluster inside those ten years. By the ownership score on this page, the most 1980s girl's name is Krystle, which ranks only 242nd by popularity. The most 1980s boy's name is Dustin, ranked 44th. The score measures how much of a name's recorded lifetime falls inside the decade, with a penalty for rare names so they cannot win on a technicality.",

      "A second pattern runs the other direction. William, Charles, and Mary all rank near the top for the decade, but they fall into the popular-but-timeless group. They were used heavily in the 1980s, yet their recorded histories are spread so evenly that no single decade owns them.",

      "The classroom example makes that easier to picture. Rebuild an average 30-student class of 1984 births from the national records, and no name is common enough to guarantee a duplicate. All 30 seats have different names. Even Michael has an expected seat count of just 0.60 across the 16 boys' seats. It only claims a seat in the reconstruction because of the leftover fraction.",

      "Spelling families tell a different story. Standard rankings count each spelling separately, so a name split across variants looks smaller than the whole pattern. Ashley alone ranks fourth among girls' names of the decade. Grouped with its five reviewed variants, the Ashley family totals 387,668 births, enough to rank third.",

      "Everything on this page comes from Social Security Administration birth records for 1980 through 1989, with lifetimes computed through 2025, the current data vintage. The source has limits. It records sex at birth rather than gender, and it suppresses any name-year count below five, so the rarest names are missing entirely. The methodology page covers both. The ownership score is a descriptive statistic about recorded births, not a judgment about what any name meant to the people who carried it.",
    ],
  },
};
