import { DECADE_HUB_DEFINITIONS } from "./content/decade-hub-definitions";
import { GENERATION_DEFINITIONS } from "./content/generation-definitions";
import { CONTENT_DEFINITIONS } from "./content/content-definitions";
import { ALL_STATES, stateToSlug } from "./us-states-map";

/** Viz pages generated by the content factory (rolloutState draft/live). */
const CONTENT_FACTORY_VIZ_SLUGS = CONTENT_DEFINITIONS.filter((d) => d.kind !== "post").map((d) => d.slug);

export type IndexableRouteFamily =
  | "static"
  | "name"
  | "year"
  | "state"
  | "decade"
  | "decade-child"
  | "generation"
  | "initial"
  | "ending"
  | "status"
  | "visualization"
  | "blog";

export interface IndexableRoute {
  path: string;
  family: IndexableRouteFamily;
  lastmod?: string;
  priority?: number;
  /** Why this route is intentionally exempt from the three-inbound-link rule. */
  linkGraphExemption?: string;
}

export interface IndexableNameInput { name: string }
export interface IndexableBlogInput { slug: string; publishedAt?: string | null }

export interface IndexableRouteOptions {
  minYear: number;
  maxYear: number;
  /** Latest year of SSA state-level data (lags maxYear by one release
   * cycle). State hub lastmod dates use it; defaults to maxYear - 1. */
  stateMaxYear?: number;
  names?: IndexableNameInput[];
  blogPosts?: IndexableBlogInput[];
  maxRoutes?: number;
}

const LETTERS = "abcdefghijklmnopqrstuvwxyz".split("");
const DECADE_CHILDREN = ["methodology", "classroom", "spelling-families"];

const STATIC_ROUTES: IndexableRoute[] = [
  { path: "/", family: "static", priority: 1 },
  ...["extinct", "endangered", "comeback", "rising", "emerging", "fading"].map((slug): IndexableRoute => ({ path: `/${slug}`, family: "status", priority: 0.7 })),
  { path: "/year", family: "static", priority: 0.7 },
  { path: "/names/", family: "static", priority: 0.7 },
  { path: "/state/", family: "static", priority: 0.7 },
  { path: "/about", family: "static", priority: 0.6 },
  { path: "/press", family: "static", priority: 0.6 },
  { path: "/developers", family: "static", priority: 0.6 },
  { path: "/blog/", family: "blog", priority: 0.7 },
  { path: "/viz/", family: "visualization", priority: 0.6 },
  ...[
    "explore", "nobody-named-2025", "debut-of-the-year", "concentration", "constellations", "crossings", "empire", "fossil",
    "gallery", "graveyard", "heartbeats", "heatwave", "kehlani-effect", "living-treemap", "naming-diversity-index", "peak-speed",
    "suffix-waves", "surge", "survival", "tenure", "terminal-letters", "velocity", "wavefront",
  ].map((slug): IndexableRoute => ({ path: `/viz/${slug}`, family: "visualization", priority: 0.5 })),
  ...["millennial-names", "gen-z-names", "classic-names", "future-grandparent-names"].map((slug): IndexableRoute => ({ path: `/${slug}`, family: "static", priority: 0.5 })),
];

/** Normalize a route path to the site's established canonical trailing-slash policy. */
export function canonicalRoutePath(path: string): string {
  const url = new URL(path, "https://nobodynamed.com");
  let pathname = url.pathname.replace(/\/{2,}/g, "/");
  if (pathname !== "/" && !pathname.endsWith("/") && !pathname.includes(".") && shouldHaveTrailingSlash(pathname)) pathname += "/";
  return pathname;
}

function shouldHaveTrailingSlash(path: string): boolean {
  return path.startsWith("/name/") || path.startsWith("/year/") || path.startsWith("/names/") || path.startsWith("/state/") || path === "/state" || path.startsWith("/blog/") || path === "/blog" || path === "/viz";
}

/** The canonical URL universe consumed by sitemap, IndexNow, and link auditing. */
export function buildIndexableRoutes(options: IndexableRouteOptions): IndexableRoute[] {
  const { minYear, maxYear } = options;
  const dataDate = `${maxYear}-05-15`;
  const routes: IndexableRoute[] = [...STATIC_ROUTES];

  // Google rejects sitemap lastmod dates before 1970 ("Invalid date" — it
  // treats pre-epoch dates as implausible). Historical year/decade pages are
  // archival content whose lastmod is a synthetic `${year}-05-15` anyway, so
  // for anything before 1970 we omit the tag rather than lie about it.
  const dataDateFor = (year: number): string | undefined => (year < 1970 ? undefined : `${year}-05-15`);
  for (let year = minYear; year <= maxYear; year++) routes.push({ path: `/year/${year}/`, family: "year", lastmod: dataDateFor(year), priority: 0.6 });
  const stateDataDate = `${options.stateMaxYear ?? maxYear - 1}-05-15`;
  for (const state of ALL_STATES) {
    routes.push({ path: `/state/${stateToSlug(state)}/`, family: "state", lastmod: stateDataDate, priority: 0.6 });
  }
  for (let decade = Math.floor(minYear / 10) * 10; decade <= Math.floor(maxYear / 10) * 10; decade += 10) {
    routes.push({ path: `/names/${decade}s/`, family: "decade", lastmod: dataDateFor(Math.min(decade + 9, maxYear)), priority: 0.5 });
  }
  const minDecade = Math.floor(minYear / 10) * 10;
  const maxDecade = Math.floor(maxYear / 10) * 10;
  for (const definition of DECADE_HUB_DEFINITIONS) {
    if (definition.rolloutState !== "seeded" || definition.startYear < minDecade || definition.startYear > maxDecade) continue;
    for (const child of DECADE_CHILDREN) {
      routes.push({ path: `/names/${definition.slug}/${child}/`, family: "decade-child", lastmod: dataDate, priority: 0.5 });
    }
  }
  for (const definition of GENERATION_DEFINITIONS) {
    if (definition.rolloutState !== "live") continue;
    routes.push({ path: `/names/${definition.slug}/`, family: "generation", lastmod: dataDate, priority: 0.5 });
  }
  for (const letter of LETTERS) {
    routes.push({ path: `/names/${letter}/`, family: "initial", lastmod: dataDate, priority: 0.4 });
    routes.push({ path: `/names/ending/${letter}/`, family: "ending", lastmod: dataDate, priority: 0.4 });
  }
  for (const post of options.blogPosts ?? []) routes.push({ path: `/blog/${encodeURIComponent(post.slug)}/`, family: "blog", lastmod: post.publishedAt?.slice(0, 10), priority: 0.7 });
  for (const slug of CONTENT_FACTORY_VIZ_SLUGS) routes.push({ path: `/viz/${slug}`, family: "visualization", priority: 0.6 });

  const maxRoutes = options.maxRoutes ?? 50_000;
  const nameCapacity = Math.max(0, maxRoutes - routes.length);
  for (const name of (options.names ?? []).slice(0, nameCapacity)) routes.push({ path: `/name/${encodeURIComponent(name.name)}/`, family: "name", lastmod: dataDate, priority: 0.8 });

  const unique = new Map<string, IndexableRoute>();
  for (const route of routes) unique.set(canonicalRoutePath(route.path), { ...route, path: canonicalRoutePath(route.path) });
  return [...unique.values()].slice(0, maxRoutes);
}

export function absoluteIndexableUrl(origin: string, path: string): string {
  const base = new URL(origin);
  if (base.hostname !== "localhost" && base.hostname !== "127.0.0.1") base.protocol = "https:";
  base.pathname = "/";
  return new URL(canonicalRoutePath(path).replace(/^\//, ""), base).toString();
}
