import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

type BlogStatus = "draft" | "published";

export type BlogPostRow = {
  slug: string;
  title: string;
  description: string;
  bodyHtml: string;
  status: BlogStatus;
  author: string;
  ogImage: string | null;
  publishedAt: string | null;
};

type Frontmatter = Record<string, string>;

const DEFAULT_AUTHOR = "NobodyNamed";
const DEFAULT_OG_IMAGE = "/api/og/default";

export function compileBlogPost(markdown: string, sourcePath: string): BlogPostRow {
  const { frontmatter, body } = splitFrontmatter(markdown);
  const title = frontmatter.title?.trim();
  if (!title) throw new Error("Blog post frontmatter must include title");

  const slug = normalizeSlug(frontmatter.slug ?? slugFromPath(sourcePath));
  const status = parseStatus(frontmatter.status);
  const bodyMarkdown = stripMatchingTitleHeading(body, title);
  const bodyHtml = markdownToHtml(bodyMarkdown);
  const description = (frontmatter.description ?? deriveDescription(bodyMarkdown)).trim();
  if (!description) throw new Error("Blog post needs a description or a prose paragraph");

  return {
    slug,
    title,
    description: truncateDescription(description),
    bodyHtml,
    status,
    author: (frontmatter.author ?? DEFAULT_AUTHOR).trim(),
    ogImage: normalizeNullable(frontmatter.og_image ?? frontmatter.ogImage) ?? DEFAULT_OG_IMAGE,
    publishedAt: parsePublishedAt(frontmatter.date ?? frontmatter.published_at ?? frontmatter.publishedAt, status),
  };
}

export function renderBlogPostSql(post: BlogPostRow): string {
  const values = [
    sqlString(post.slug),
    sqlString(post.title),
    sqlString(post.description),
    sqlString(post.bodyHtml),
    sqlString(post.status),
    sqlString(post.author),
    sqlString(post.ogImage),
    sqlString(post.publishedAt),
  ].join(", ");

  return `-- Generated by scripts/blog-publish.ts.
-- Review, then apply with:
--   npm run blog:apply:local -- <this-file>
--   npm run blog:apply:remote -- <this-file>

PRAGMA foreign_keys = ON;

INSERT INTO blog_posts(slug, title, description, body_html, status, author, og_image, published_at, updated_at)
VALUES (${values}, datetime('now'))
ON CONFLICT(slug) DO UPDATE SET
  title=excluded.title,
  description=excluded.description,
  body_html=excluded.body_html,
  status=excluded.status,
  author=excluded.author,
  og_image=excluded.og_image,
  published_at=excluded.published_at,
  updated_at=datetime('now');
`;
}

export function defaultMigrationName(slug: string, now = new Date()): string {
  const timestamp = now
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "");
  return `${timestamp}_publish_${slug.replace(/-/g, "_")}.sql`;
}

function splitFrontmatter(markdown: string): { frontmatter: Frontmatter; body: string } {
  const normalized = markdown.replace(/\r\n?/g, "\n");
  if (!normalized.startsWith("---\n")) return { frontmatter: {}, body: normalized };

  const end = normalized.indexOf("\n---", 4);
  if (end === -1) throw new Error("Unclosed frontmatter block");

  const raw = normalized.slice(4, end).trim();
  const bodyStart = normalized.indexOf("\n", end + 4);
  const body = bodyStart === -1 ? "" : normalized.slice(bodyStart + 1);
  return { frontmatter: parseFrontmatter(raw), body };
}

function parseFrontmatter(raw: string): Frontmatter {
  const data: Frontmatter = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const match = /^([A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(.*)$/.exec(trimmed);
    if (!match) throw new Error(`Invalid frontmatter line: ${line}`);
    data[match[1]] = stripYamlScalarQuotes(match[2].trim());
  }
  return data;
}

function stripYamlScalarQuotes(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function slugFromPath(sourcePath: string): string {
  return path.basename(sourcePath, path.extname(sourcePath));
}

function normalizeSlug(slug: string): string {
  const normalized = slug
    .trim()
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(normalized)) {
    throw new Error(`Invalid blog slug: ${slug}`);
  }
  return normalized;
}

function parseStatus(value: string | undefined): BlogStatus {
  if (!value) return "published";
  if (value === "draft" || value === "published") return value;
  throw new Error(`Invalid blog status: ${value}`);
}

function parsePublishedAt(value: string | undefined, status: BlogStatus): string | null {
  if (!value) return status === "draft" ? null : new Date().toISOString();
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return `${value}T09:00:00.000Z`;

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) throw new Error(`Invalid publish date: ${value}`);
  return date.toISOString();
}

function normalizeNullable(value: string | undefined): string | null {
  const trimmed = value?.trim();
  if (!trimmed || trimmed.toLowerCase() === "null") return null;
  return trimmed;
}

function stripMatchingTitleHeading(markdown: string, title: string): string {
  const lines = markdown.replace(/\r\n?/g, "\n").split("\n");
  let index = 0;
  while (index < lines.length && !lines[index].trim()) index++;

  const first = lines[index]?.trim();
  if (first?.startsWith("# ")) {
    const heading = first.replace(/^#\s+/, "").trim();
    if (heading === title) lines.splice(index, 1);
  }
  return lines.join("\n").trim();
}

function markdownToHtml(markdown: string): string {
  const lines = markdown.replace(/\r\n?/g, "\n").split("\n");
  const blocks: string[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];
    const trimmed = line.trim();

    if (!trimmed) {
      index++;
      continue;
    }

    if (/^(---|\*\*\*)$/.test(trimmed)) {
      blocks.push("<hr>");
      index++;
      continue;
    }

    if (startsRawHtmlBlock(trimmed)) {
      const htmlLines: string[] = [];
      while (index < lines.length && lines[index].trim()) {
        htmlLines.push(lines[index]);
        index++;
      }
      blocks.push(htmlLines.join("\n"));
      continue;
    }

    const heading = /^(#{1,6})\s+(.+)$/.exec(trimmed);
    if (heading) {
      const level = heading[1].length;
      blocks.push(`<h${level}>${renderInline(heading[2])}</h${level}>`);
      index++;
      continue;
    }

    if (isTableStart(lines, index)) {
      const { html, nextIndex } = renderTable(lines, index);
      blocks.push(html);
      index = nextIndex;
      continue;
    }

    if (/^[-*]\s+/.test(trimmed)) {
      const items: string[] = [];
      while (index < lines.length && /^[-*]\s+/.test(lines[index].trim())) {
        items.push(`<li>${renderInline(lines[index].trim().replace(/^[-*]\s+/, ""))}</li>`);
        index++;
      }
      blocks.push(`<ul>\n${items.join("\n")}\n</ul>`);
      continue;
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      const items: string[] = [];
      while (index < lines.length && /^\d+\.\s+/.test(lines[index].trim())) {
        items.push(`<li>${renderInline(lines[index].trim().replace(/^\d+\.\s+/, ""))}</li>`);
        index++;
      }
      blocks.push(`<ol>\n${items.join("\n")}\n</ol>`);
      continue;
    }

    if (/^>\s?/.test(trimmed)) {
      const quote: string[] = [];
      while (index < lines.length && /^>\s?/.test(lines[index].trim())) {
        quote.push(lines[index].trim().replace(/^>\s?/, ""));
        index++;
      }
      blocks.push(`<blockquote>\n<p>${renderInline(quote.join(" "))}</p>\n</blockquote>`);
      continue;
    }

    const paragraph: string[] = [];
    while (index < lines.length && lines[index].trim() && !isBlockBoundary(lines, index)) {
      paragraph.push(lines[index].trim());
      index++;
    }
    blocks.push(`<p>${renderInline(paragraph.join(" "))}</p>`);
  }

  return blocks.join("\n");
}

function isBlockBoundary(lines: string[], index: number): boolean {
  const trimmed = lines[index].trim();
  return (
    /^(#{1,6})\s+/.test(trimmed) ||
    /^(---|\*\*\*)$/.test(trimmed) ||
    startsRawHtmlBlock(trimmed) ||
    isTableStart(lines, index) ||
    /^[-*]\s+/.test(trimmed) ||
    /^\d+\.\s+/.test(trimmed) ||
    /^>\s?/.test(trimmed)
  );
}

function startsRawHtmlBlock(trimmed: string): boolean {
  return /^<\/?(div|section|figure|figcaption|table|thead|tbody|tr|td|th|p|ul|ol|li|blockquote|script|style)\b/i.test(trimmed);
}

function isTableStart(lines: string[], index: number): boolean {
  const row = lines[index]?.trim();
  const separator = lines[index + 1]?.trim();
  return Boolean(
    row?.includes("|") &&
      separator &&
      /^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(separator),
  );
}

function renderTable(lines: string[], startIndex: number): { html: string; nextIndex: number } {
  const rows: string[][] = [];
  let index = startIndex;

  while (index < lines.length && lines[index].trim().includes("|")) {
    if (index !== startIndex + 1) rows.push(splitTableRow(lines[index].trim()));
    index++;
  }

  const [head = [], ...body] = rows;
  const headHtml = head.map((cell) => `<th>${renderInline(cell)}</th>`).join("");
  const bodyHtml = body
    .map((row) => `<tr>${row.map((cell) => `<td>${renderInline(cell)}</td>`).join("")}</tr>`)
    .join("\n");

  return {
    html: `<table>\n<thead><tr>${headHtml}</tr></thead>\n<tbody>\n${bodyHtml}\n</tbody>\n</table>`,
    nextIndex: index,
  };
}

function splitTableRow(row: string): string[] {
  return row
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function renderInline(text: string): string {
  const tokens: string[] = [];
  const token = (html: string): string => {
    const id = tokens.length;
    tokens.push(html);
    return `\u0000${id}\u0000`;
  };

  let rendered = text.replace(/`([^`]+)`/g, (_match, code: string) => token(`<code>${escapeHtml(code)}</code>`));
  rendered = rendered.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (_match, label: string, url: string) =>
    token(`<a href="${escapeAttribute(sanitizeUrl(url))}">${renderInline(label)}</a>`),
  );

  rendered = escapeHtml(rendered)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>");

  return rendered.replace(/\u0000(\d+)\u0000/g, (_match, id: string) => tokens[Number(id)]);
}

function sanitizeUrl(url: string): string {
  if (/^(https?:\/\/|\/|#)/.test(url)) return url;
  throw new Error(`Unsupported link URL: ${url}`);
}

function deriveDescription(markdown: string): string {
  const lines = markdown.replace(/\r\n?/g, "\n").split("\n");
  let paragraph: string[] = [];

  for (let index = 0; index < lines.length; index++) {
    const trimmed = lines[index].trim();
    if (!trimmed) {
      if (paragraph.length) break;
      continue;
    }
    if (
      /^(#{1,6})\s+/.test(trimmed) ||
      /^[-*]\s+/.test(trimmed) ||
      /^\d+\.\s+/.test(trimmed) ||
      /^>\s?/.test(trimmed) ||
      startsRawHtmlBlock(trimmed) ||
      isTableStart(lines, index)
    ) {
      if (paragraph.length) break;
      continue;
    }
    paragraph.push(trimmed);
  }

  return stripInlineMarkdown(paragraph.join(" "));
}

function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[`*_]/g, "")
    .replace(/<[^>]+>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function truncateDescription(description: string): string {
  const normalized = description.replace(/\s+/g, " ").trim();
  if (normalized.length <= 155) return normalized;
  return `${normalized.slice(0, 152).trimEnd()}...`;
}

function sqlString(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/"/g, "&quot;");
}

async function main(args: string[]): Promise<void> {
  const input = readInput(args);
  if (!input || args.includes("--help") || args.includes("-h")) {
    printUsage();
    process.exit(input ? 0 : 1);
  }

  const stdout = args.includes("--stdout");
  const checkOnly = args.includes("--check");
  const outDir = readOption(args, "--out") ?? "migrations";
  const source = await readFile(input, "utf8");
  const post = compileBlogPost(source, input);
  const sql = renderBlogPostSql(post);

  if (checkOnly) {
    console.log(`OK ${post.slug}: ${post.title}`);
    return;
  }

  if (stdout) {
    process.stdout.write(sql);
    return;
  }

  const filename = defaultMigrationName(post.slug);
  const outPath = path.join(outDir, filename);
  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, sql, "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(`Local apply: npm run blog:apply:local -- ${outPath}`);
  console.log(`Remote apply: npm run blog:apply:remote -- ${outPath}`);
}

function readInput(args: string[]): string | undefined {
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === "--out") {
      index++;
      continue;
    }
    if (arg && !arg.startsWith("--")) return arg;
  }
  return undefined;
}

function readOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index === -1) return undefined;
  const value = args[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`${name} needs a value`);
  return value;
}

function printUsage(): void {
  console.error(`Usage: tsx scripts/blog-publish.ts <content/blog/post.md> [--out migrations] [--stdout] [--check]

Frontmatter:
  title: "Post title"             required
  date: "2026-05-24"              optional; YYYY-MM-DD publishes at 09:00 UTC
  slug: "custom-slug"             optional; defaults to filename
  description: "Meta description" optional; defaults to first prose paragraph
  author: "NobodyNamed"           optional
  status: "published"             optional; published or draft
  og_image: "/api/og/default"     optional
`);
}

const entrypoint = process.argv[1];
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  main(process.argv.slice(2)).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
