// Regenerates packages/shared/src/common-word-names.ts: every word in
// dicts/2of12.txt that is also an SSA first name with fewer than
// COMMON_WORD_NAME_CEILING recorded births (legacy shards, 1880–2017).
// The blog auto-linker skips these at the start of a sentence, where
// capitalization says nothing ("Add every spelling", "Baby-name consultant").
//
//   npx tsx scripts/build-common-word-names.ts

import fs from "node:fs";
import path from "node:path";

const ROOT = path.join(__dirname, "..");
const CEILING = 50_000;

const dict = new Set(
  fs
    .readFileSync(path.join(ROOT, "dicts/2of12.txt"), "utf8")
    .split(/\r?\n/)
    .map((w) => w.trim())
    .filter((w) => /^[a-z]+$/.test(w)),
);

const totals = new Map<string, number>();
const shardDir = path.join(ROOT, "viz/name-vitals/data/names");
for (const file of fs.readdirSync(shardDir).filter((f) => f.endsWith(".json"))) {
  const shard = JSON.parse(fs.readFileSync(path.join(shardDir, file), "utf8")) as { n: Record<string, number[]> };
  for (const [key, arr] of Object.entries(shard.n)) {
    const lower = key.split("|")[0]!.toLowerCase();
    // arr[0] is the series start year; the rest are yearly counts.
    const sum = arr.slice(1).reduce((a, b) => a + b, 0);
    totals.set(lower, (totals.get(lower) ?? 0) + sum);
  }
}

const words = [...dict].filter((w) => (totals.get(w) ?? CEILING) < CEILING).sort();
const lines: string[] = [];
for (let i = 0; i < words.length; i += 12) lines.push("  " + words.slice(i, i + 12).map((w) => JSON.stringify(w)).join(", ") + ",");

const out = `// GENERATED by scripts/build-common-word-names.ts — do not edit by hand.
//
// Common English words (dicts/2of12.txt) that are also SSA first names with
// fewer than ${CEILING.toLocaleString("en-US")} recorded births (1880–2017 legacy shards). ${words.length} words.

export const COMMON_WORD_NAMES: ReadonlySet<string> = new Set([
${lines.join("\n")}
]);
`;
fs.writeFileSync(path.join(ROOT, "packages/shared/src/common-word-names.ts"), out);
console.log(`wrote ${words.length} words`);
